### ISSUE TITLE
commit d160706f295d8c58c4e605f8b62773fc4528486d breaks build on APPLE

### ISSUE THREAD

**Issue by herc4mac** [hercules-390/hyperion#110]
In file included from hsys.c:12:
In file included from ./hercules.h:146:
In file included from ./hstructs.h:19:
./telnet.h:355:5: error: declaration of anonymous struct must be a definition
    struct error_t
    ^
./telnet.h:364:10: error: type name requires a specifier or qualifier
    error;
         ^

**Comment by Fish-Git** [comment]
So fix it! You're a Hercules developer!

**Comment by herc4mac** [comment]
very dirty...
error_t is typedeffed sopmewhere 
and the two definition clash
