### ISSUE TITLE
HERCULES_CNF ignored with build 8473

### ISSUE THREAD

**Issue by erwinmars** [hercules-390/hyperion#129]
After my last upgrade to build 8473 my hercules start no more works, because the config file was not loaded. After i moved it to the -f parm on the command line it was loaded. Btw. the HERCULES_RC environment variable has worked.

[startmvs.zip](https://github.com/hercules-390/hyperion/files/288457/startmvs.zip)

**Comment by Fish-Git** [comment]
Fixed in commit 9997d0750917632b6b8a46af741b4e75bafc7f23.
