### ISSUE TITLE
scpimply on - Not honored any more ?

### ISSUE THREAD

**Issue by fbi-ranger** [hercules-390/hyperion#130]
scpimply on passed automatically all commands not understood by Hercules to the guest system. 
Seems that this not working any more. 

It is necessary to put / in a command to pass it to the guest os. 

I IPLed DDR to make a standalone restore. Now I do have to prefix every command with '/'

**Comment by Fish-Git** [comment]
I believe you are mistaking [Integrated Console printer-keyboard device command prefixes](http://hercules-390.github.io/html/hercconf.html#consysc) with Hercules panel command implied SCP (System Control Program) replies:

```
HHC01603I help scpimply
HHC01603I
HHC01602I Command      Description
HHC01602I -------      -------------------------------------------------------
HHC01602I scpimply    *Set/Display option to pass non-hercules commands to the scp
HHC01603I
HHC01603I Format: "scpimply [ on | off ]"
HHC01603I When scpimply is set ON, non-hercules commands are passed to
HHC01603I the scp if the scp has enabled receipt of scp commands. The
HHC01603I default is off. When scpimply is entered without any options,
HHC01603I the current state is displayed.
HHC01603I
HHC01603I help .reply
HHC01603I
HHC01602I Command      Description
HHC01602I -------      -------------------------------------------------------
HHC01602I .reply      *SCP command
HHC01603I
HHC01603I To reply to a system control program (i.e. guest operating system)
HHC01603I message that gets issued to the hercules console, prefix the reply
HHC01603I with a period.
HHC01603I
HHC01603I help !message
HHC01603I
HHC01602I Command      Description
HHC01602I -------      -------------------------------------------------------
HHC01602I !message    *SCP priority message
HHC01603I
HHC01603I To enter a system control program (i.e. guest operating system)
HHC01603I priority command on the hercules console, simply prefix the command
HHC01603I with an exclamation point '!'.
HHC01603I
```

To send a reply to the SCP from the HMC (Hardware Maintenance Console, i.e. the Hercules panel interface) you need to prefix your reply with a `.` dot or period. (To send an unsolicited message to the SCP prefix your message with a `!` bang or  exclamation point instead.)

To reply to a Integrated Console printer-keyboard device from the HMC you need to prefix your reply with the device's defined command prefix character.
