### ISSUE TITLE
HHC00136E Error in function WinMsgThread: CreateWindowEx() failed

### ISSUE THREAD

**Issue by Peter-J-Jansen** [hercules-390/hyperion#139]
After (almost) every first restart of a freshly re-built Hercules, error message `HHC00136E` occurs, after which it then terminates:

    18:54:39 HHC01413I Hercules version 4.0.0.8583-g784eca3 (4.0.0.8583)
    ...
    18:54:40 HHC00151I Activated facility: Message Security Assist Extension 1, 2, 3 and 4   
    18:54:40 HHC00136E Error in function WinMsgThread: CreateWindowEx() failed
    18:54:40 HHC01420I Begin Hercules shutdown
    18:54:40 HHC01423I Calling termination routines
    18:54:40 HHC02103I Logger: logger thread terminating

Most of the times, restarting Hercules just a 2nd time will work fine. But if the 2nd retry does not fix it, then further retries won't help, only a Windows (10) reboot fixes it then, but again, only after on the 2nd Hercules start.

**Comment by Fish-Git** [comment]
Wow! I can't believe I wrote such absolutely _crappy_, _amateurish_ code! It's absolutely _horrible!_ Using a "Sleep(100)" for thread synchronization?! Sheesh! What's wrong with me?!

In any case, give me a few minutes to fix it for you. When you see me make the commit with the fix in it, do a pull and rebuild and accept my apologies for introducing such crappy code into Hercules in the first place.
