### ISSUE TITLE
Some easy ones

### ISSUE THREAD

**Issue by PeterCoghlan** [hercules-390/hyperion#148]
I thought I'd compile recent hyperion on my VMS system and see if I can find the telnet problem that is causing so much heat on the mailing list.  One of the virtues of using an unusual compiler is that I get some warnings and informational messages that don't get generated by the more usual compilers.  Here are a few of the smaller problems.  None of these is at all serious - they just make it harder to spot the real problems in among them. I will open new issues for the more difficult ones.

In channel.c, there are 3 invocations of CASSERT() with extraneous trailing semicolons on lines 142, 143 and 144.

In ctcadpt.c:
static void*  CTCT_ListenThread( void* argp )
^
%CC-W-MISSINGRETURN, Non-void function "CTCT_ListenThread" does not contain a return statement. at line number 1325 in file ctcadpt.c

static void*  CTCE_ListenThread( void* argp )
^
%CC-W-MISSINGRETURN, Non-void function "CTCE_ListenThread" does not contain a return statement. at line number 2072 in file ctcadpt.c

In scedasd.c:

Two invocations of CASSERT() with extraneous trailing semicolons at lines 123 and 124.

In tapedev.c:

One invocation of CASSERT() with an extraneous trailing semicolon at line 587.

In opcode.c:

56 invocations of DISASM_PRINT() and 7 of UNDEF_INST() with extraneous trailing semicolons.

**Comment by Fish-Git** [comment]
Thanks Peter!

Fixing UNREACHABLE_CODE however isn't going to be easy.

**Comment by PeterCoghlan** [comment]
Many thanks.

The "extraneous semicolon" messages and "non-void function does not contain a return" messages are all gone away now.
