### ISSUE TITLE
Compiles fail on platforms which don't have semaphore.h

### ISSUE THREAD

**Issue by PeterCoghlan** [hercules-390/hyperion#155]
In hstdinc.h, there is:
```
#include <semaphore.h>
```
It is enclosed in `#if !defined(_MSVC_) / #endif` but this assumes that all other platforms provide this file, otherwise hacking the source is required to get pretty much anything to compile.

Is this used for anything? Searching for "semaphore" in the source only results on one hit on message HHC02340 in msgenu.h and I don't see this message referenced elsewhere.  Maybe the #include and message are leftovers from something which is no longer used and can be removed entirely?

If the `#include` is required for something, can we have a `HAVE_SEMAPHORE_H` flag or something similar here?

**Comment by PeterCoghlan** [comment]
The above should say hash include open angle bracket semaphore.h close angle bracket but the github webserver appears to have eaten the angle brackets and filename between them.

**Comment by jphartmann** [comment]
Ah, the joys of markdown.  Anything that remotely resembles programming should be enclosed in backticks.  Single backtick for inline; three for a group of lines.  So here is a bunch of lines with a single backtick; I don't think it is possible to show one inline.
```
`
```
I've updated the above append to show what you wanted to express.

I think the `#include` is a leftover from one of my failed attempts to use a particular type of semaphore that then turned out to be implemented on top of something that I absolutely did not want.  Please remove it (can you?)

**Comment by PeterCoghlan** [comment]
Thanks John!

I can't remove it myself.  Could you do it please?

(Perhaps the HHC02340 message should also be removed?)

**Comment by jphartmann** [comment]
Done including message.

**Comment by Fish-Git** [comment]
> The above should say hash include open angle bracket semaphore.h close angle bracket but the github webserver appears to have eaten the angle brackets and filename between them.

You need to use the HTML escapes `'&lt;'` and `'&gt;'`, e.g.:

"If the #include&lt;semaphore.h&gt; is required for something,..."

**Comment by ivan-w** [comment]
This is a github issue !

Github should sanitize user/external input so as to prevent various 
issues (sql injection, Javascript execution on client, etc).

;DROP TABLE USERS;

:P

--Ivan

**Comment by Fish-Git** [comment]
> Github should sanitize user/external input

Isn't that what it is doing?

**Comment by Fish-Git** [comment]
> ;DROP TABLE USERS;

https://xkcd.com/327/

**Comment by Fish-Git** [comment]
Returning back to the original issue for a brief moment, should this issue be closed now that it has been resolved?

**Comment by PeterCoghlan** [comment]
I have to run now and don't have time to test.  I will assume that all will be well and close the issue now.  I will reopen it if there are any problems when I test it later.
