### ISSUE TITLE
Bare r command on Hercules console with no argument causes crash due to access violation

### ISSUE THREAD

**Issue by PeterCoghlan** [hercules-390/hyperion#157]
The debugger shows the access violation happens at the sscanf() call in parse_range() in hsemisc.c due to operand being null.

There are no problems with the v and u commands which also call parse_range() but these have a check for argc being anything other than 1 before calling parse_range() and issue an error message if this is not the case.

**Comment by jphartmann** [comment]
Please pull and retest.

**Comment by PeterCoghlan** [comment]
Many thanks.

An r command on it's own now results in the message:

``HHC17000E Missing or invalid argument(s)``

and no crash.

However, an r command followed by more than one whitespace delimited argument is accepted and the second and subsequent arguments either do nothing or have some effect which is not mentioned in the help text.

**Comment by jphartmann** [comment]
Please pull and retest.

**Comment by PeterCoghlan** [comment]
Many thanks.  All looks good now.
