### ISSUE TITLE
_dynamic_version fails to execute on FreeBSD

### ISSUE THREAD

**Issue by jphartmann** [hercules-390/hyperion#174]
Reason is that the hash bang wants /bin/bash.  But `pkg install bash` puts it in /usr/local/bin.

The idea is to create a header file that contains information that might as well be in configure.  It is definitely the wrong tool for the job.

Like an old loved dog, it should be taken out in the yard and shot;  though another Danish idiom springs to mind in this particular context.

Current thinking is to obtain the desired information, namely the commit level, from the post-commit git hook.  Then people who do not obtain hyperion by git clone/pull are not inconvenienced.  That hook could also run autogen, when needed, whichever way that can be determined.

The Hyperion startup message will be changed to include the complete commit hash.

This clearly depends on the ability to implement the post commit hook on windows.

**Comment by jphartmann** [comment]
Git hooks cannot be forced on anyone, so anything that deals with this problem must be a shell script, and it must be written as a Bourne script to be executable anywhere.

Anyhow, using the  post-commit hook clearly introduces a chicken-and-egg situation since whatever is written to contain the commit hash must also be committed.  But there are other commit hooks to explore, but I wonder if the problem is not intractable; adding something to a commit will change its hash.

**Comment by srorso** [comment]
Hi John:  I believe you dropped _dynamic_version from open source builds.  Can this be closed?

**Comment by jphartmann** [comment]
This has been fixed by rewriting and fixing zillions of bugs.  The operative is now GetGitHash, which is what it does.

Changes:

1.  The version numbers are now generated from configure.ac to config.h, so no need to provide then in some parallel way.

2.  Git information is obtained from documented primary interfaces without mucking about in the git state.

**Comment by jphartmann** [comment]
Yes, Steve.

_dynamic_load (Q licence) is in UNIX replaced by GetGitHash (public 
domain).  I'm done with GetGitHash, if that is your question.  Ah, issue 
174?  Yup.  Is now closed.
