### ISSUE TITLE
macOS 10.13.3 Clang - Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by zebuscat** [hercules-390/hyperion#246]
Hi,
trying to compile 'Commit 23-01-2018' gives me the following error:

clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
Undefined symbols for architecture x86_64:
  "_pthread_getcpuclockid", referenced from:
      _configure_cpu in libherc.a(config.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [hercules] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

I am using these compiler options:
CFLAGS="-O3 -D_FORTIFY_SOURCE=0" CC="gcc" ../../hyperion/configure --enable-optimization="-O3 -mtune=native -fomit-frame-pointer -Wunreachable-code" --enable-het-bzip2 --enable-cckd-bzip2 --enable-ipv6
make

No issues with 'Commit 27-11-2017' here.

Dirk

**Comment by Peter-J-Jansen** [comment]
I am sorry to admit that my fix for the incorrect getrusage() following the suggestion in Issue #217 overlooked the absence of pthread_getcpuclokid() in macOS and some other Unix implementations. What may be possible in those cases is to revert to using host_tod() instead as the incorrect getrusage() originally did. Better solutions are suggested in issue #217 by superdave.
However, I do not have macOS available to me to perform this task, so this may take some time for me to correct this situation.
Peter J.

**Comment by herc4mac** [comment]
How difficult would it be to check for the pthread_getcpuclockid
and ifdef accordingly,
or quick and dirty…  ifdef __APPLE__

we have lived with the error for a long time, 
and looks like nobody with an apple has had the need to run a 2nd level zVM
so leaving things as they were before might not hurt anybody for a while
  

I looked at it but without a  more deep knowledge of the logic I thought it would be  a waste of time even to try.
cheers
e

**Comment by ivan-w** [comment]
Ackkk ! Please ! No OS specific detection macros in the code... That's why we have autoconf !

Leaving things as before breaks EVERY attempt at running a second level z/VM (not only on apple). It breaks on linux, on Windows...

**Comment by herc4mac** [comment]
looks like You did not care to try understand my reply…
it was simply a suggestion for QUICK AND DIRTY workaround to disable the code on APPLE 
until a PROPER correct solution could be implemented

**Comment by ivan-w** [comment]
The problem is that it probably also breaks on other OSes (xxxBSD notably)

**Comment by herc4mac** [comment]
I agree on that…
the real problem is that the configuration process is still a bit murky
configure.ac is almost abandoned and the CMAKE process is not strong enough yet IMO

**Comment by ivan-w** [comment]
autoconf ? abandoned ? says YOU ! But let's not dwell into that here or now.

So for the time being we'll have to resort to autoconf - since it works.

**Comment by srorso** [comment]
Issue also affects Solaris 11.3 / gcc 4.8.2.  No hurry on a resolution for me, though.

**Comment by srorso** [comment]
Commit a457c40 appears to have addressed the issue on Solaris.

**Comment by zebuscat** [comment]
Same here - macOS 10.13.3 Clang now compiles the new cut - no errors so far. Thanx Dirk
