### ISSUE TITLE
autoconf errors - Linux version 3.13.4  (Nitrous cloud service)

### ISSUE THREAD

**Issue by mstram** [hercules-390/hyperion#26]
$ autoconf --version
autoconf (GNU Autoconf) 2.68

$ cat /proc/version
Linux version 3.13.4 (root@ip-10-130-115-186) (gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) ) #1 SMP Mon Mar 3 09:07:22 UTC 2014

configure.ac:1043: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:194: AC_LANG_CONFTEST is expanded from...  
../../lib/autoconf/general.m4:2591: _AC_COMPILE_IFELSE is expanded from...  
../../lib/autoconf/general.m4:2607: AC_COMPILE_IFELSE is expanded from...  
../../lib/m4sugar/m4sh.m4:606: AS_IF is expanded from...  
../../lib/autoconf/general.m4:2032: AC_CACHE_VAL is expanded from...  
../../lib/autoconf/general.m4:2053: AC_CACHE_CHECK is expanded from...  
configure.ac:1043: the top level  
configure.ac:1091: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body  
../../lib/autoconf/lang.m4:194: AC_LANG_CONFTEST is expanded from...  
../../lib/autoconf/general.m4:2591: _AC_COMPILE_IFELSE is expanded from...  
../../lib/autoconf/general.m4:2607: AC_COMPILE_IFELSE is expanded from...  
../../lib/m4sugar/m4sh.m4:606: AS_IF is expanded from...  
../../lib/autoconf/general.m4:2032: AC_CACHE_VAL is expanded from...  
../../lib/autoconf/general.m4:2053: AC_CACHE_CHECK is expanded from...  
configure.ac:1091: the top level  
configure.ac:1235: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body  
../../lib/autoconf/lang.m4:194: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2591: _AC_COMPILE_IFELSE is expanded from...  
../../lib/autoconf/general.m4:2607: AC_COMPILE_IFELSE is expanded from...  
../../lib/m4sugar/m4sh.m4:606: AS_IF is expanded from...  
../../lib/autoconf/general.m4:2032: AC_CACHE_VAL is expanded from...  
../../lib/autoconf/general.m4:2053: AC_CACHE_CHECK is expanded from...  
configure.ac:1235: the top level  
configure.ac:1287: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body  
../../lib/autoconf/lang.m4:194: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2591: _AC_COMPILE_IFELSE is expanded from...
../../lib/autoconf/general.m4:2607: AC_COMPILE_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:606: AS_IF is expanded from...
../../lib/autoconf/general.m4:2032: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2053: AC_CACHE_CHECK is expanded from...
configure.ac:1287: the top level

configure.ac:12: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:14: error: possibly undefined macro: AM_MAINTAINER_MODE
configure.ac:212: error: possibly undefined macro: AC_LIBTOOL_DLOPEN
configure.ac:233: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
configure.ac:240: error: possibly undefined macro: AC_DISABLE_STATIC
configure.ac:258: error: possibly undefined macro: AC_PROG_LIBTOOL
configure.ac:345: error: possibly undefined macro: AC_LIB_LTDL
configure.ac:2227: error: possibly undefined macro: AM_CONDITIONAL

**Comment by Fish-Git** [comment]
> Le 04/08/2014 10:38, Mike Stramba a écrit :
> Yep.. You are correct...
> 
> I was looking at the spinhawk one... the "hyperion" thingy no longer
> contains the correct instructions.
> 
> Why this instruction was removed, I have no idea...
> 
> This is getting ridiculous

I'm not sure where you two are getting your information from but _BOTH_ Hypersion _and_ Spinhawk have had the `./autogen.sh` step mentioned in their INSTALL document (file) since virtually day one, and at _no time_ was it ever removed by anyone.

So neither of you are right.

**Comment by Fish-Git2** [comment]
[...]
> I'm not sure where you two are getting your information from
> but BOTH Hypersion and Spinhawk have had the ./autogen.sh step
> mentioned in their INSTALL document (file) since virtually day
> one, and at no time was it ever removed by anyone.
> 
> So neither of you are right.

This comment was made in error and has now been deleted.

My sincerest apologies to those concerned.

-- 
"Fish" (David B. Trout)
Software Development Laboratories
http://www.softdevlabs.com
mail: fish@softdevlabs.com
