### ISSUE TITLE
1403 printers won't work under z/VM 5.3 

### ISSUE THREAD

**Issue by vinatron** [hercules-390/hyperion#265]
Hello I have been using vm under Hercules 3.x and 1403 printers work but when I use Hercules 4.0 1403 printers do not show up under vm as spool devices what cotcause this thanks Vincent

**Comment by jphartmann** [comment]
Old unit record devices, such as 1403 and reader-punch, do not respond to sense operation E4.  They must be defined in the system configuration file.

Alternatively, you can use `legacysen` to "upgrade" the old devices to react to the E4 command:

```
HHC01603I legacysen       
HHC02203I legacysenseid : disabled 
```

Legacy sense might have been enabled on earlier 3.x releases.
