### ISSUE TITLE
Hang in Hercules taking a Standalone Dump

### ISSUE THREAD

**Issue by davekreiss** [hercules-390/hyperion#279]
David,

I am running MVS 3.8 with modifications and took a wait state 009064 (S0C4 in NIP) during IPL to a 3390 SYSRES. I have previously built a standalone dump on a 3350 (device 153) and written 4 tape marks to the output dump aws tape (a 3420 at 480). After the wait state I do a store status (STORE command) successfully. I then mount the standalone dump output tape on 480 (via a devinit). I then IPL 153 and Hercules hangs. I have done this quite a few times and did one time get a dump on 480. Don't ask what I did correctly or why it worked that one time, I don't know what I might have done differently.

[Hercules.Hang.Doc.zip](https://github.com/hercules-390/hyperion/files/4137375/Hercules.Hang.Doc.zip)

So again here is what I did:

IPL 19F got disabled wait state 00020000 80090064
store
devinit 480 "\Program Files\Hercules\Tape\sad.aws" awstape
IPL 153
I get a prompt on the 3277 at 010 to which I reply
Instruction counter does nothing and Hercules console doesn't respond. I entered several quit commands to no avail.
I do a windows close (right click on ICON) and select close.
Enclosed is the Hercules log, my IPL batch file, the configuration in a zip file.

I am running the latest (I think) pre-built Hercules-4.2.1.9826 in a DOS window.
Operating system is Windows 10 latest (build 1909).

Let me know what else you might need.

Dave Kreiss

**Comment by Fish-Git** [comment]
&nbsp;
_**You have created your GitHub Issue in the wrong place.**_

Please note the that the following two URLs are _not_ the same:

* https://github.com/hercules-390/hyperion/issues &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; _(old/unsupported Hercules)_
* https://github.com/SDL-Hercules-390/hyperion/issues &nbsp; _(current supported version of Hercules)_

The place where you have created your issue (i.e. here) is for an old version of Hercules that is no longer supported by anyone. It's an old dead version of Hercules.

Problems with the _**SDL**_ version of Hercules 4.x Hyperion however -- _(which is the only current, actively developed, fully supported version of Hercules in existence and appears to be the version you are using)_ -- should be reported _**here**_ instead:

* _**[https://github.com/SDL-Hercules-390/hyperion/issues](https://github.com/SDL-Hercules-390/hyperion/issues)**_
