### ISSUE TITLE
DASDCOMP Message HHC02424E against 3380 created volume

### ISSUE THREAD

**Issue by davekreiss** [hercules-390/hyperion#280]
I created a 3380 dasd volume using DASDINIT then immediately did a DASDCOMP and received message HHC02424E.

PC OS is Windows 10 and the commands issued were DASDINIT and DASDCOMP from command line. Those commands and resulting messages follow.

C:\Program Files\Hercules\Hercules>DASDINIT -a "C:/Program Files/Hercules/Dasd/RES380.3380" 3380-J RES380
HHC02499I Hercules utility dasdinit - DASD image file creation program - version 4.2.0.9708-SDL-gdc7243b2
HHC01414I (C) Copyright 1999-2019 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SoftDevLabs version of Hercules **
HHC01415I Build date: Jul 8 2019 at 12:19:44
HHC00467W Maximum cylinders supported is 65536
HHC00007I Previous message from function 'create_ckd' at dasdutil.c(1848)
HHC00462I 0:0000 CKD file C:/Program Files/Hercules/Dasd/RES380.3380: creating 3380 volume RES380: 886 cyls, 15 trks/cyl, 47616 bytes/track
HHC00460I 0:0000 CKD file C:/Program Files/Hercules/Dasd/RES380.3380: 886 cylinders successfully written
HHC02423I DASD operation completed

C:\Program Files\Hercules\Hercules>CCKDCOMP -3 "C:/Program Files/Hercules/Dasd/RES380.3380"
HHC02499I Hercules utility cckdcomp - CCKD compress program - version 4.2.0.9708-SDL-gdc7243b2
HHC01414I (C) Copyright 1999-2019 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SoftDevLabs version of Hercules **
HHC01415I Build date: Jul 8 2019 at 12:19:44
HHC02424E Dasd image file format unsupported or unrecognized: C:/Program Files/Hercules/Dasd/RES380.3380
HHC00007I Previous message from function 'main' at cckdcomp.c(99)

C:\Program Files\Hercules\Hercules>

Hopefully that is sufficient to determine what is happening. Note that I tried variations of 3380-J -E and -K with and without specifying alternate tracks with same results.

Let me know if there is any more info you might need.

Dave Kreiss

**Comment by Fish-Git** [comment]
&nbsp;
_**You have created your GitHub Issue in the wrong place.**_

Please note the that the following two URLs are _not_ the same:

* https://github.com/hercules-390/hyperion/issues &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; _(old/unsupported Hercules)_
* https://github.com/SDL-Hercules-390/hyperion/issues &nbsp; _(current supported version of Hercules)_

The place where you have created your issue (i.e. here) is for an old version of Hercules that is no longer supported by anyone. It's an old dead version of Hercules.

Problems with the _**SDL**_ version of Hercules 4.x Hyperion however -- _(which is the only current, actively developed, fully supported version of Hercules in existence and appears to be the version you are using)_ -- should be reported _**here**_ instead:

* _**[https://github.com/SDL-Hercules-390/hyperion/issues](https://github.com/SDL-Hercules-390/hyperion/issues)**_
