### ISSUE TITLE
Date and Time are Undocumented HERCLOGO Variables

### ISSUE THREAD

**Issue by Neo-Desktop** [hercules-390/hyperion#281]
Just a heads up, the following variables are not defined in the [HERCLOGO Readme](https://github.com/hercules-390/hyperion/blob/d15e28f8ba22d9665f4535f596b9cb7ec077a7d2/README.HERCLOGO)

The links show how they're implemented in `hscutl`.`get_symbol()`

Variable Name | Date | Time
--------|-----------------|-----------
HERCLOGO Statement | [$(DATE)](https://github.com/hercules-390/hyperion/blob/d15e28f8ba22d9665f4535f596b9cb7ec077a7d2/hscutl.c#L423) | [$(TIME)](https://github.com/hercules-390/hyperion/blob/d15e28f8ba22d9665f4535f596b9cb7ec077a7d2/hscutl.c#L431)
strftime() format | `%Y%m%d` | `%H%M%S`
logical evaluation | `YYYYMMDD` | `HHMMSS`
Example | `20200321` | `153336`

**Comment by Neo-Desktop** [comment]
Furthermore, `$(DATE)` and `$(TIME)` don't show up in `DEFSYM`
`$(CUU)`, `$(CCUU)`, and `$(DEVN)` do, however

**Comment by Fish-Git** [comment]
FYI:

https://github.com/SDL-Hercules-390/hyperion/blob/master/readme/README.HERCLOGO.md

**Comment by Fish-Git** [comment]
FYI #&#x2060;2:

[hercules-390/hyperion](https://github.com/hercules-390/hyperion) is commonly considered to be a dead Hercules project (no longer actively maintained).

[SDL-Hercules-390/hyperion](https://github.com/SDL-Hercules-390) however, is not, and is commonly considered to be the only actively maintained Hercules project currently in existence.

**Comment by Neo-Desktop** [comment]
Awsome thank you Fish
