### ISSUE TITLE
Undocumented DASDCOPY features and restrictions

### ISSUE THREAD

**Issue by Neo-Desktop** [hercules-390/hyperion#282]
**This references a [14(!) year old thread on yahoo groups](https://hercules-390.yahoogroups.narkive.com/4VAConcS/combining-split-3390-3-dasd)**

### Situation 1:

> dasdcopy -o ckd -lfs DISK_1.3390 NEWDISK.3390
> 
> the `-lfs' means make one large file. When DISK_1.3390 is opened, the
> code is smart enough to open DISK_2.3390 too.

This enhancement to the `-lfs` switch is undocumented

------------

### Situation 2:

> I tried using the -bz2 option, too, to get the file size
> down, but dasdcopy keeps printing the usage as if it's an unrecognized
> option

This is still accurate as of today
Expected: explanation as to why the -bz2 option is unrecognized

Explanation:
> The -bz2 parameter is incompatible with -lfs (-lfs implies ckd) and with
> `-o ckd' (which specifies ckd).

This also implies that `-lfs` is not compatible with `-o CCKD`

------------

### Lastly:

> There's been enough confusion about this (dasdcopy just printing the
> syntax whenever conflicting operands are entered) that I will try to fix
> the code to give a more meaningful error message.

I agree, the way this is currently implemented is really confusing and requires a google search for why things aren't working intuitively

Furthermore, on principle, 14-year-old bugs should be fixed

**Comment by Fish-Git** [comment]
_**FYI:**_

[hercules-390/hyperion](https://github.com/hercules-390/hyperion) is commonly considered to be a dead Hercules project (no longer actively maintained).

[**SDL-Hercules-390/hyperion**](https://github.com/SDL-Hercules-390) however, is not, and is commonly considered to be the only _actively_ maintained Hercules project currently in existence.

Have you investigated the SDL version of `dasdcopy`? I believe it might behave better.

If it doesn't however, then please submit a new GitHub Issue in [_**SDL Hyperion's github issue tracker**_](https://github.com/SDL-Hercules-390/hyperion/issues)_, NOT here._ Generally speaking, we're much more responsive to problem reports and don't typically let them sit for 14 years.

**Comment by Neo-Desktop** [comment]
Will do, thanks again @Fish-Git
