### ISSUE TITLE
Processor CP00: Addressing exception code 0005  ilc 6 when installing MVS 3.8

### ISSUE THREAD

**Issue by MockbaTheBorg** [hercules-390/hyperion#283]
Hi there,

I am using Hyperion to install MVS 3.8j. I am following the steps from here:
http://www.jaymoseley.com/hercules/installMVS/iStarter.htm
However once I get past the first step (start) in order use smp4 to build the distribution libraries, I get a lot of errors, starting with the one in the description.
I have attached the log file for the start procedure, and the smp4 log file from after I type "ipl 150".
I have attached also a .zip file with the disks I created, I am creating pre_steps and post_steps disks for in case I need to repeat any.
I have followed the instructions to the dot, tried different folders, ran both as elevated mode and not-elevated, but nothing seems to change the behavior.
I am a hercules noob, so I am not sure if the initial process could be a problem, though the log doesn't seem to show any issue there.
I am posting here in the hope that someone could point me to something obvious I am forgetting to do, or some clue which would allow me to follow the steps.
On Jay's page there's a reference to Hyperion "SDL" 4.3.999, but I could't find it.

Thanks a lot,
Marcelo "Mockba the Borg" Dantas.

[dasd.zip](https://github.com/hercules-390/hyperion/files/4467278/dasd.zip)

[start.log](https://github.com/hercules-390/hyperion/files/4467272/start.log)
[smp4_a.log](https://github.com/hercules-390/hyperion/files/4467274/smp4_a.log)

**Comment by MockbaTheBorg** [comment]
I was able to resolve this. No need to track it here.
Thanks a lot.

**Comment by dlrourke** [comment]
Hi there.  It might help others to know what you did to resolve your error.  Thanks.

**Comment by Fish-Git** [comment]
Mockba the Borg wrote:

[...]
> On Jay's page there's a reference to
> Hyperion "SDL" 4.3.999, but I could't find it.

FYI:

Main web page:

  https://sdl-hercules-390.github.io/html/


What's New:

  https://sdl-hercules-390.github.io/html/hercnew.html


Source code:

  https://github.com/sdl-hercules-390/hyperion

-- 
"Fish" (David B. Trout)
Software Development Laboratories
http://www.softdevlabs.com
mail: fish@softdevlabs.com

**Comment by Fish-Git** [comment]
Also:

README:

* https://github.com/SDL-Hercules-390/hyperion/blob/master/README.md

**Comment by MockbaTheBorg** [comment]
> Hi there. It might help others to know what you did to resolve your error. Thanks.

I actually did nothing. As no one replied I just ignored the errors and moved on with the installation, which ended up working fine.

Thanks,
Marcelo

**Comment by ivan-w** [comment]
Just thinking out loud here but.. but usually a PIC 5  (Addressing Exception) during initialization is the very naive way of early operating systems to determine storage size ;)  and can be safely ignored as it is expected. (This also lead to an unexpected behavior of some OSes getting confused when there is actually 16MB of storage as the PIC5 never occurs because - poof - wraparound)

**Comment by MockbaTheBorg** [comment]
Maybe ... but as I had no idea, and Google didn't help much either, I just moved on in the hopes that things would work fine, and so they did.
