### ISSUE TITLE
AUTOMOUNT does not manage concatenation of root directory with files concatenation

### ISSUE THREAD

**Issue by marXtevens** [hercules-390/hyperion#286]
It appears that by making use of AUTOMOUNT to have a root directory, breaks the ability to actually attach an existing file to an OS, presenting an empty file instead.

This is from a current build of SDL-Hyperion. The information is in the attached log file.

I set up hard and symbolic links for a tape (AWS) file. The following are the hard and symbolic links on the host Linux for Hercules.

> [xmas@vm370dev VM370]$ find /home -iname '*CUNY*.aws'
> /home/xmas/Hercules/VM370/Tapes/_CUNYMODS.aws
> /home/xmas/Hercules/VM370/VM_370_Utilities/CUNY/_CUNYMODS.aws
> [xmas@vm370dev VM370]$ ls -l /home/xmas/Hercules/VM370/Tapes/_CUNYMODS.aws /home/xmas/Hercules/VM370/VM_370_Utilities/CUNY/_CUNYMODS.aws
> lrwxrwxrwx. 1 xmas xmas     61 Feb  8 14:37 /home/xmas/Hercules/VM370/Tapes/_CUNYMODS.aws -> /home/xmas/Hercules/VM370/VM_370_Utilities/CUNY/_CUNYMODS.aws
> -rw-r--r--. 1 xmas xmas 302718 May 22  2017 /home/xmas/Hercules/VM370/VM_370_Utilities/CUNY/_CUNYMODS.aws
> [xmas@vm370dev VM370]$ 

Log on as MAINT. Absolute path to the file via DEVINIT.

> HHC01018I 0:01C0 COMM: client 192.168.122.1 devtype 3270: connected
> /20:32:51 GRAF 1C0 LOGON  AS MAINT    USERS = 004
> HHC01603I DEVINIT 580 /home/xmas/Hercules/VM370/VM_370_Utilities/CUNY/_CUNYMODS.aws
> HHC00221I 0:0580 Tape file /home/xmas/Hercules/VM370/VM_370_Utilities/CUNY/_CUNYMODS.aws, type AWS: format type AWS Format tape file
> HHC02245I 0:0580 device initialized
> /CP ATTACH 580 MAINT 181
> /20:41:37 
> /20:41:37 TAPE 580 ATTACH TO MAINT    181
> 

Screen scraping of MAINT console showing tape attached, and output from TAPE SCAN and TAPEMAP commands.

> Ready(00028); T=0.01/0.01 20:40:19
> TAPE 181 ATTACHED
> tape rew (tap1
> Ready; T=0.01/0.01 20:41:47
> tape scan (tap1
>  SCANNING....
> INVALID RECORD FORMAT.
> Ready(00032); T=0.01/0.01 20:41:54
> tape rew (tap1
> Ready; T=0.01/0.01 20:41:59
> tapemap
> TapeMap 3.1                     CONVERSATIONAL MONITOR SYSTEM
>  
> No options were specified.
> The input tape is on a 3420-8  9-track tape drive at address 0181.
> The tape was recorded at 6250 bpi and is in  unlabeled  format.
> No volume name can be determined.
> **** File      1.
>      This file is apparently in VMFPLC2  (4K)  format.
>      FileName FileType FM Format LRecL    Records Date     Time
>      CMS      EXEC     A1 F         80          7 01/09/02 09:10
>      CUNYMODS DOCUMENT A1 F         80         24 03/03/81 17:58
>      DMKALG   CNY27    A1 F         80          1 11/05/80 15:15
>      DMKCFC   CNY09    A1 F         80          1 10/31/80 12:19
>      DMKCFT   CNY05    A1 F         80          2 11/10/80 13:29
>      DMKCFT   CNY19    A1 F         80         15 11/06/80 13:47
>      DMKCNS   CNY05    A1 F         80          2 11/10/80 13:46
>      DMKCNS   CNY19    A1 F         80         17 11/06/80 16:39
>      DMKCQR   CNY05    A1 F         80          1 11/10/80 14:56
>      DMKCQR   CNY06    A1 F         80          4 11/05/80 16:13
>      DMKCQR   CNY19    A1 F         80          5 11/06/80 11:30
>      DMKCQY   CNY07    A1 F         80          4 11/10/80 11:02
>      DMKCQY   CNY14    A1 F         80          3 01/22/81 17:45
>      DMKDIA   CNY14    A1 F         80          2 01/22/81 17:21
>      DMKDIA   CNY16    A1 F         80          1 12/26/80 13:18
>      DMKGRF   CNY16    A1 F         80          6 01/06/81 13:57
> 
>                                                             HOLDING
> ...
>      End of file       1 encountered after reading     176 blocks
>      containing     294K bytes.  About   12 feet of tape was used.
>      The largest block was  4,005 bytes, the last block was
>       1,605 bytes, and the smallest block was     77 bytes.
> **** File      2.
>      End of file       2 encountered after reading       0 blocks
>      containing under 1K bytes.  About    1 foot of tape was used.
> **** Logical End-of-Tape
> TapeMap read     176 blocks containing     294K bytes.  There
> were       2 files.  About   12 feet of tape was used.
> End of TapeMap execution.
> Ready; T=0.03/0.13 20:44:44

Tape detached and new file attached. This one uses symlink.

> HHC01018I 0:01C0 COMM: client 192.168.122.1 devtype 3270: connected
> /20:32:51 GRAF 1C0 LOGON  AS MAINT    USERS = 004
> HHC01603I DEVINIT 580 /home/xmas/Hercules/VM370/VM_370_Utilities/CUNY/_CUNYMODS.aws
> HHC00221I 0:0580 Tape file /home/xmas/Hercules/VM370/VM_370_Utilities/CUNY/_CUNYMODS.aws, type AWS: format type AWS Format tape file
> HHC02245I 0:0580 device initialized
> /CP ATTACH 580 MAINT 181
> /20:41:37 
> /20:41:37 TAPE 580 ATTACH TO MAINT    181

Again, screen scraping from MAINT console shows tape can be read by
TAPMAP, and not by TAPE SCAN.

> cp detach 181
> TAPE 181 DETACHED
> Ready; T=0.01/0.01 20:49:43
> TAPE 181 ATTACHED
> tape rew (tap1
> Ready; T=0.01/0.01 20:51:02
> tape scan (tap1
>  SCANNING....
> INVALID RECORD FORMAT.
> Ready(00032); T=0.01/0.01 20:51:09
> tape rew (tap1
> Ready; T=0.01/0.01 20:51:18
> tapemap
> TapeMap 3.1                     CONVERSATIONAL MONITOR SYSTEM
>  
> No options were specified.
> The input tape is on a 3420-8  9-track tape drive at address 0181.
> The tape was recorded at 6250 bpi and is in  unlabeled  format.
> No volume name can be determined.
> **** File      1.
>      This file is apparently in VMFPLC2  (4K)  format.
>      FileName FileType FM Format LRecL    Records Date     Time
>      CMS      EXEC     A1 F         80          7 01/09/02 09:10
>      CUNYMODS DOCUMENT A1 F         80         24 03/03/81 17:58
>      DMKALG   CNY27    A1 F         80          1 11/05/80 15:15
>      DMKCFC   CNY09    A1 F         80          1 10/31/80 12:19
>      DMKCFT   CNY05    A1 F         80          2 11/10/80 13:29
>      DMKCFT   CNY19    A1 F         80         15 11/06/80 13:47
>      DMKCNS   CNY05    A1 F         80          2 11/10/80 13:46
>      DMKCNS   CNY19    A1 F         80         17 11/06/80 16:39
>      DMKCQR   CNY05    A1 F         80          1 11/10/80 14:56
>      DMKCQR   CNY06    A1 F         80          4 11/05/80 16:13
>      DMKCQR   CNY19    A1 F         80          5 11/06/80 11:30
>      DMKCQY   CNY07    A1 F         80          4 11/10/80 11:02
>      DMKCQY   CNY14    A1 F         80          3 01/22/81 17:45
>      DMKDIA   CNY14    A1 F         80          2 01/22/81 17:21
>      DMKDIA   CNY16    A1 F         80          1 12/26/80 13:18
>      DMKGRF   CNY16    A1 F         80          6 01/06/81 13:57
>      DMKLNK   CNY00    A1 F         80          1 11/19/80 16:11
>      DMKLOG   CNY27    A1 F         80          2 11/05/80 15:29
>      DMKLOH   CNY16    A1 F         80          1 12/26/80 10:34
> 
>                                                             HOLDING
> ...
>      End of file       1 encountered after reading     176 blocks
>      containing     294K bytes.  About   12 feet of tape was used.
>      The largest block was  4,005 bytes, the last block was
>       1,605 bytes, and the smallest block was     77 bytes.
> **** File      2.
>      End of file       2 encountered after reading       0 blocks
>      containing under 1K bytes.  About    1 foot of tape was used.
> **** Logical End-of-Tape
> TapeMap read     176 blocks containing     294K bytes.  There
> were       2 files.  About   12 feet of tape was used.
> End of TapeMap execution.
> Ready; T=0.03/0.16 20:53:54

I set up AUTOMOUNT to the original file, DEVINIT shows an extra message this time: "HHC00235I 0:0580 Tape file _CUNYMODS.aws, type aws: tape created"

> HHC01603I AUTOMOUNT ADD /home/xmas/Hercules/VM370/VM_370_Utilities/CUNY/
> HHC02203I default allowed automount directory: /home/xmas/Hercules/VM370/VM_370_Utilities/CUNY/
> HHC01603I DEVINIT 580 _CUNYMODS.aws
> HHC00221I 0:0580 Tape file _CUNYMODS.aws, type AWS: format type AWS Format tape file
> HHC00235I 0:0580 Tape file _CUNYMODS.aws, type aws: tape created
> HHC02245I 0:0580 device initialized
> /CP ATTACH 580 MAINT 181
> /20:57:37 
> /20:57:37 TAPE 580 ATTACH TO MAINT    181

This time we see the tape is empty.

> cp detach 181
> TAPE 181 DETACHED
> Ready; T=0.01/0.01 20:54:31
> tape rew (tap1
> DMSTPE113S 'TAP1(181)' NOT ATTACHED.
> Ready(00100); T=0.01/0.01 20:57:23
> TAPE 181 ATTACHED
> tape rew (tap1
> Ready; T=0.01/0.01 20:57:57
> tape scan (tap1
>  SCANNING....
>  END-OF-FILE OR END-OF-TAPE
> Ready(00028); T=0.01/0.01 20:58:13
> tape rew (tap1
> Ready; T=0.01/0.01 21:01:43
> tapemap
> TapeMap 3.1                     CONVERSATIONAL MONITOR SYSTEM
>  
> No options were specified.
> The input tape is on a 3420-8  9-track tape drive at address 0181.
> **** End-of-File Encountered
> **** End-of-File Encountered
> The tape was recorded at 6250 bpi and is in  unlabeled  format.
> **** Logical End-of-Tape
> TapeMap read       0 blocks containing under 1K bytes.  There
> were       0 files.  About    1 foot of tape was used.
> End of TapeMap execution.
> Ready; T=0.01/0.01 21:01:50

Again, the attached tape is empty.

> CP DETACH 181
> TAPE 181 DETACHED
> Ready; T=0.01/0.01 21:07:57
> DMSTPE113S 'TAP1(181)' NOT ATTACHED.
> Ready(00100); T=0.01/0.01 21:07:57
> TAPE 181 ATTACHED
> tape rew (tap1
> Ready; T=0.01/0.01 21:08:39
> tape scan (tap1
>  SCANNING....
>  END-OF-FILE OR END-OF-TAPE
> Ready(00028); T=0.01/0.01 21:08:59
> tape rew (tap1
> Ready; T=0.01/0.01 21:09:13
> tapemap
> TapeMap 3.1                     CONVERSATIONAL MONITOR SYSTEM
>  
> No options were specified.
> The input tape is on a 3420-8  9-track tape drive at address 0181.
> **** End-of-File Encountered
> **** End-of-File Encountered
> The tape was recorded at 6250 bpi and is in  unlabeled  format.
> **** Logical End-of-Tape
> TapeMap read       0 blocks containing under 1K bytes.  There
> were       0 files.  About    1 foot of tape was used.
> End of TapeMap execution.
> Ready; T=0.01/0.01 21:09:20

The complete hercules log file is attached.
[2021-02-08.vm370dev.marXtevens.strangled.net.zip](https://github.com/hercules-390/hyperion/files/5946895/2021-02-08.vm370dev.marXtevens.strangled.net.zip)

**Comment by Fish-Git** [comment]
https://github.com/hercules-390/hyperion/issues/280#issuecomment-580571989

**Comment by marXtevens** [comment]
Thanks for the pointer to the correct place. Posted in the wrong place. Closed.
