### ISSUE TITLE
Hercules cannot work with libnsl.so.3

### ISSUE THREAD

**Issue by rachejazz** [hercules-390/hyperion#289]
```
$ dasdinit -linux -lfs SUSE.disk 3390-9 ROOT
dasdinit: error while loading shared libraries: libnsl.so.2: cannot open shared object file: No such file or directory
```
I am using Arch, my lib directory:
![image](https://user-images.githubusercontent.com/42383989/137198720-370bfa07-8150-4d86-b5e8-2f2ee8e58a20.png)

Is there any fix to this? Like can it be safe to make a sym link between so.3 and so.2?

Digging into what version of libnsl I am using, I got this:
```
╰──> λ pacman -Ss libnsl
core/libnsl 2.0.0-1 [installed]
    Public client interface library for NIS(YP)
```

**Comment by wrljet** [comment]
Divya,

What Arch version are you running?

Bill

**Comment by rachejazz** [comment]
Rolling distro Bill, I'm on 5.14.11 currently :)

**Comment by rachejazz** [comment]
This issue got solved by applying symlink and a rebuild of dasdinit!
```
ln -s /usr/lib/libnsl-2.33.so /usr/lib/libnsl.so.2
ldd /usr/bin/dasdinit
```
