### ISSUE TITLE
Linux: Scrambled input via Webserver Command input field

### ISSUE THREAD

**Issue by truda** [hercules-390/hyperion#50]
When entering certain commands in the webserver the input is scrambled:

-> /V 010,CONSOLE,AUTH=ALL
 returns
/V 010,conso,AUTH%3=L

OS tested: linux (Ubuntu (gcc 4.8.2) and Debian 8 (gcc 4.9.2)) on x86_64 arch.
Scramble also apparent in the Spinhawk version and the Ubuntu packaged binary (V3.07).

**Comment by Fish-Git** [comment]
Fixed by commit 93c9f367cecc800156f7d22e32acaa1e43d7eb57
