### ISSUE TITLE
webserver device tab -> segmentation fault with 3705 device in config

### ISSUE THREAD

**Issue by truda** [hercules-390/hyperion#51]
After adding a 3705 to the config file *0664 3705 lport=3705*
you may experience a segfault when clicking on the devices tab in hercules web server.
Behavior reported on:
hercules hyperion running under linux.
has been observed with some older versions of hercules too.

**Comment by Fish-Git** [comment]
Gert Caers wrote:

> After adding a 3705 to the config file 0664 3705 lport=3705
> you may experience a segfault when clicking on the devices
> tab in hercules web server.
> 
> Behavior reported on: hercules hyperion running under linux.
> has been observed with some older versions of hercules too.

Fixed by commit 76b31f5e2172f567a7437cc2d6b299569442c3f4.

-- 
"Fish" (David B. Trout)
Software Development Laboratories
http://www.softdevlabs.com
mail: fish@softdevlabs.com
