### ISSUE TITLE
Not allowed to set LP2 extended rights (Z/OS)

### ISSUE THREAD

**Issue by Vf58** [hercules-390/hyperion#54]
Hello
Is it already an option to set that or is it not yet implemented?
Thank you

**Comment by Fish-Git** [comment]
This does not appear to be a Hercules 4.0 (Hyperion) issue. It appears to be a poorly asked (unclear) question regarding z/OS.

If you feel this is truly a Hercules (4.0 Hyperion) problem that is perhaps preventing you from doing something that is valid in z/OS, then you need to provide a more detailed explaination of the problem/issue as well as strong evidence of your claim.

Until then, I am closing this issue as: Invalid + Won't Fix.

Feel free to re-open it once you have more evidence of (and a better (more clear) description of) the problem.

**Comment by Vf58** [comment]
Hello,


I understand your point of view.
This message is received when starting an Adabas database. It checks the licence status, Serial Number, Msu... Same is working well on a 'non-emulated' hardware.
It's not really a problem, I was just curious to check Adabas and Natural...

Thank you.
