### ISSUE TITLE
Linux X64 compile errors

### ISSUE THREAD

**Issue by vbcoen** [hercules-390/hyperion#55]
Downloaded current repo code and under Mageia v4 X64 get largish number of build warnings such as:
-------------------------------------
hexdumpe.c: In function ‘_hexdumpxn’:
hexdumpe.c:148:9: warning: format ‘%llX’ expects argument of type ‘long long unsigned int’, but argument 5 has type ‘U64’ [-Wformat=]
         sprintf( &p[0], "%s%0*llX  ", pfx, hxd, adr );
         ^
hexdumpe.c:155:9: warning: format ‘%llX’ expects argument of type ‘long long unsigned int’, but argument 5 has type ‘U64’ [-Wformat=]
         sprintf( &p[0], "%s%0*llX  ", pfx, hxd, adr );
         ^
hthreads.c: In function ‘loglock’:
hthreads.c:83:5: warning: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 6 has type ‘pthread_t’ [-Wformat=]
     WRMSG( HHC90013, "E", calltype, ilk->name, rc, err_desc,
... more similar then:   ----

ltdl.c: In function ‘rpl_strdup’:
ltdl.c:287:7: warning: implicit declaration of function ‘strlcpy’ [-Wimplicit-function-declaration]
       strlcpy(tmp, str, strlen(str)+1);
       ^
ltdl.c: In function ‘presym_close’:
ltdl.c:2099:16: warning: parameter ‘module’ set but not used [-Wunused-but-set-parameter]
      lt_module module;
                ^
ltdl.c: In function ‘lt_dlopenext’:
ltdl.c:3498:5: warning: implicit declaration of function ‘strlcat’ [-Wimplicit-function-declaration]
     strlcat (tmp, archive_ext, tsize );
     ^
 .. more of the same then ---

cpu.c: In function ‘s370_run_cpu’:
cpu.c:1669:18: warning: variable ‘regs’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Wclobbered]
 register REGS   *regs;
                  ^
In file included from cpu.c:1857:0:
cpu.c: In function ‘s390_run_cpu’:
cpu.c:1669:18: warning: variable ‘regs’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Wclobbered]
 register REGS   *regs;
                  ^
In file included from cpu.c:1863:0:
cpu.c: In function ‘z900_run_cpu’:
cpu.c:1669:18: warning: variable ‘regs’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Wclobbered]
 register REGS   *regs;
                  ^
timer.c: In function ‘timer_update_thread’:
timer.c:203:5: warning: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘TID’ [-Wformat=]
     WRMSG (HHC00100, "I", thread_id(), get_thread_priority(0), "Timer");
     ^
--- more of the same then ---

In file included from hercules.h:148:0,
                 from cckddiag.c:19:
cckddiag.c: In function ‘decomptrk’:
msgenu.h:81:60: warning: argument to ‘sizeof’ in ‘snprintf’ call is the same expression as the destination; did you mean to provide an explicit length? [-Wsizeof-pointer-memaccess]
 #define MSGBUF( _buf, ... )           snprintf(_buf, sizeof(_buf), ## __VA_ARGS__ )
                                                            ^
cckddiag.c:181:17: note: in expansion of macro ‘MSGBUF’
                 MSGBUF(msg, "%s %d uncompress error, rc=%d;"
                 ^
msgenu.h:81:60: warning: argument to ‘sizeof’ in ‘snprintf’ call is the same expression as the destination; did you mean to provide an explicit length? [-Wsizeof-pointer-memaccess]
 #define MSGBUF( _buf, ... )           snprintf(_buf, sizeof(_buf), ## __VA_ARGS__ )
                                                            ^
cckddiag.c:202:17: note: in expansion of macro ‘MSGBUF’
                 MSGBUF(msg, "%s %d decompress error, rc=%d;"
                 ^
------------------------------------- 

Might be a problem relating to wrong source library in use but what ?

**Comment by Fish-Git** [comment]
"Move along. Nothing to see here."

None of the warnings you are seeing are anything to worry about. gcc is just being overly pedantic (as usual), that's all.
