### ISSUE TITLE
Incorrect instruction trace operand data and "u" command disassembles incorrect virtual page

### ISSUE THREAD

**Issue by Fish-Git** [hercules-390/hyperion#56]
Peter Coghlan reports in **_spinhawk_** issue **39**:

> When tracing instructions or single stepping, incorrect instruction
> operand data can sometimes be displayed on the Hercules console.
> The data is incorrect because it is from the wrong virtual page. This
> is due to a stale page table entry being retrieved from a temporary
> translation lookaside buffer in translate_addr() due in turn to
> regs->tlbID being set to zero which appears to not be valid. Before
> calling translate_addr(), a temporary copy is made of part of the regs
> structure by copy_regs() but tlbID is not copied (because it appears in
> the regs structure after regs_copy_end) and the temporary tlbID is not
> initialised.
> 
> The "u" command is similarly affected in that it can end up
> disassembling code from the wrong virtual page.
> 
> The "v" command is not affected as it bypasses the temporary TLB.
> 
> Data used for actual instruction execution is not affected because
> regs->tlbID is never zero when this is being fetched.
> 
> S/370 mode and S/390 mode are both affected. I have not tested in
> Z/Arch mode.
> 
> The bug is elusive and difficult to provoke. It appears to only affects
> pages which have been remapped at least once. Fixed pages in an
> operating system kernel for example are not affected.
> 
> One possible fix appears to be to use ARCH_DEP(purge_tlb) to clear the
> new temporary TLBs in copy_regs() instead of memset(). Another possible
> fix is to always bypass use of the temporary TLB for data displayed on
> the Hercules console in the same way the "v" command does by calling
> virt_to_abs(), display_virt() etc with ACCTYPE_LRA instead of
> ACCTYPE_READ or ACCTYPE_INSTFETCH.
> 
> Some further thought may be required about the involvement of TLBs in
> fetching data to be displayed on the Hercules console.

Additionally, in the main _hercules-390_ support forum thread entitled **"Incorrect operand data in instruction trace"**, Peter reported his further analysis of the issue:

> A while ago, I wrote:
>
> > To recap on what the problem is as it's been a while: Operand
> > data is sometimes incorrectly displayed when tracing instructions
> > and single stepping. The data is read from the wrong virtual page.
> > The 'u' command is also affected - it disassebles code from the
> > wrong virtual page. Both errors seem to happen when virt_to_abs()
> > is called with acctype set to ACCTYPE_READ but not when acctype
> > is set to ACCTYPE_LRA.
>
> I think I have now figured out what the problem is but I am not
> sure I am right and if I am right, I am not sure how to fix it.
> I would appreciate it if someone more familiar with with Hercules
> internals could check my logic. I think the following applies to
> pretty much any version of Hercules in recent years although the
> problem does not show up in all versions and variants and I haven't
> gone digging into all of them to see if there are subtle variations.
> 
> I studied the code some more and figured out that virt_to_abs()
> calls logical_to_main() which eventually calls translate_addr()
> in dat.h and the actual address translation is carried out in
> this function.
> 
> I added some debugging messages to translate_addr() and recompiled
> hscmisc.c (only). This revealed that when the problem occurred,
> translate_addr() was retrieving from the translation lookaside buffer
> a page table entry which referred to the wrong virtual page. I found
> that the reason for the incorrect PTE being returned was that
> regs->tlbID was set to zero and this broke the test for whether
> a TLB entry was valid or not (I think).
> 
> However, the 'tlb' command on the Hercules console never showed up
> the invalid TLB entries and never showed any TLB entries with 'id'
> set to zero either.
> 
> Then I found that display_inst() and disasm_stor() cause
> translate_addr() to eventually be called with a copy of part of
> the regs structure, not the real regs structure (display_inst()
> even seems to try to copy it twice!). The copy is made by a
> function called copy_regs() which copies the first part of the
> regs structure up to the location of regs_copy_end. After
> regs_copy_end are some opcode table pointers, the TLB and critically,
> tlbID. copy_regs() zeros the TLB in the new regs structure but
> does nothing with tlbID. It appears tlbID ends up with whatever
> happened to be in the memory that came from malloc() and if this
> ever happens to be zero, the bug is triggered.
> 
> Maybe calling purge_tlb() in copy_regs() would be a better way
> to clear the TLB copy and initialise the copy of tlbID ensuring
> it was never set to zero?
> 
> Or maybe tlbID should be moved up above regs_copy_end ensuring
> it gets copied to the new regs structure? Would this adversely
> affect anything else which uses copy_regs(), regs_copy_end or
> regs_copy_len which is derived from it? Would it actually fix
> the bug?
> 
> Maybe calling virt_to_abs() with acctype set to ACCTYPE_LRA to
> avoid any TLB interaction would be preferable in the case of all
> Hercules console data display? Or would this sometimes give
> misleading information? Might it show different data on the Hercules
> console to the actual data used by the instruction obtained by way
> of the (real) TLB?
> 
> Or maybe a new acctype should be defined which allows Hercules
> console commands to read data from the real TLB but not update it?
> (On second thoughts, maybe this would not work as I think
> instruction tracing can display instructions and data before they
> are executed and the real TLB would not necessarily have the
> correct data before the instruction is executed.)
> 
> Any thoughts?
> 
> Regards,
> Peter Coghlan.

While Peter did report several posts earlier in the same thread he was never able to cause the problem to occur in Hyperion (except in one dubious instance), a brief examination of Hyperion code  reveals the issue _MAY_ well exist in the Hyperion as well (at least based on his bug analysis anyway), and thus at least merits further research. If research determines the bug exists it will of course be fixed ASAP.

Thank you Peter for reporting this issue and especially for your detailed research into it.

**Comment by Fish-Git** [comment]
Temporarily STALLED due to (temporary?) lack of resources. I need to finished recovering my hardware disaster first. Will resume once recovery is complete.

**Comment by Fish-Git** [comment]
No longer stalled as I realized I don't actually need any dasd image files to research this issue. All I actually need is a .RC test script and Hercules itself (which thankfully was not destroyed in the disaster).

**Comment by Fish-Git** [comment]
I have completed my research and the bug is _exactly_ as Peter described: when the REGS struct's "tlbID" field happens to be zero after calling the "copy_regs" function (which "display_inst", "ARCH_DEP(display_inst)", "alter_display_virt", and "disasm_stor" all do), the bug occurs.

If the REGS struct's "tlbID" field happens to be anything else (non-zero), it does not occur.

I was able to easily reproduce the bug using the following patch and test script:

(First, the temporary patch I used to recreate or fix the problem with):

    From: "Peter Coghlan" <mailinglists@beyondthepale.ie>
    Date: Sat, 04 Jul 2015 15:25:27 -0800
    Subject: [PATCH] Fix incorrect instruction trace operand data display:

    Closes github issue #56.

    Bug was causing the display of instruction tracing operand data (as well as "u" (disassemble) and "r" (display real) command output too) to all sometimes access the wrong real page of storage.

    See github issue #56 for details.


    diff -r -a -x .git -x 'msvc.AMD64.*' -x 'msvc.dllmod.*' -x 'msvc.debug.*' -x '*.suo' -x '*.ncb' -x '*.user' -x '*.htm' -x WORK -x DICTS -x FILES -Nu hercules-0/hscmisc.c hercules-#56/hscmisc.c
    --- hercules-0/hscmisc.c	2015-01-25 17:08:52.473496800 -0800
    +++ hercules-#56/hscmisc.c	2015-07-04 14:51:29.664686300 -0700
    @@ -819,9 +819,30 @@
             return NULL;
         }
     
    +
    +#define BREAKIT     0
    +#define FIXIT       1
    +
    +
    +
    +#define DOWHAT      BREAKIT
    +//#define DOWHAT      FIXIT
    +
    +
    +
    +
         /* Perform partial copy and clear the TLB */
         memcpy(newregs, regs, sysblk.regs_copy_len);
         memset(&newregs->tlb.vaddr, 0, TLBN * sizeof(DW));
    +
    +
    +#if DOWHAT == FIXIT
    +    newregs->tlbID = 1;
    +#elif DOWHAT == BREAKIT
    +    newregs->tlbID = 0;
    +#endif
    +
    +
         newregs->ghostregs = 1;
         newregs->hostregs = newregs;
         newregs->guestregs = NULL;
    @@ -834,6 +855,15 @@
             hostregs = newregs + 1;
             memcpy(hostregs, regs->hostregs, sysblk.regs_copy_len);
             memset(&hostregs->tlb.vaddr, 0, TLBN * sizeof(DW));
    +
    +
    +#if DOWHAT == FIXIT
    +        hostregs->tlbID = 1;
    +#elif DOWHAT == BREAKIT
    +        hostregs->tlbID = 0;
    +#endif
    +
    +
             hostregs->ghostregs = 1;
             hostregs->hostregs = hostregs;
             hostregs->guestregs = newregs;

(Next,  the test script I used to recreate the bug and to prove the fix):



    #########  BEGIN TEST #56  #########
    #########  BEGIN TEST #56  #########
    #########  BEGIN TEST #56  #########


    msglvl -debug
    panrate fast
    stopall

    mainsize 1
    sysclear

    archmode esa/390
    sysreset


    # Low core PSWs...

    r 00=0008000080000200       # Restart PSW --> x'200'  (no DAT yet!)
    r 68=000A00008000DEAD       # ProgChk PSW (FAIL!)


    # Working storage...

    r 300=00B00000              # CR0 = DAT format control
    r 400=040A000080000000      # Successful completion PSW (with DAT still on)
    r 600=00001000              # CR1 PSTO
    r 700=040800008000021C      # DAT enabled PSW
    r A00=00003000              # New PTE #2 --> Test page #3


    # Segment table (and Test page #1)...

    r 1000=00001040             #  0:  PTO
    r 1004=00000020             #  1:  (invalid)
    r 1008=00000020             #  2:  (invalid)
    r 100C=00000020             #  3:  (invalid)
    r 1010=00000020             #  4:  (invalid)
    r 1014=00000020             #  5:  (invalid)
    r 1018=00000020             #  6:  (invalid)
    r 101C=00000020             #  7:  (invalid)
    r 1020=00000020             #  8:  (invalid)
    r 1024=00000020             #  9:  (invalid)
    r 1028=00000020             # 10:  (invalid)
    r 102C=00000020             # 11:  (invalid)
    r 1030=00000020             # 12:  (invalid)
    r 1034=00000020             # 13:  (invalid)
    r 1038=00000020             # 14:  (invalid)
    r 103C=00000020             # 15:  (invalid)


    # Page table...

    r 1040=00000000             #  0:  x'0000'
    r 1044=00001000             #  1:  x'1000'
    r 1048=00002000             #  2:  x'2000'    (later changed to x'3000')
    r 104C=00000400             #  3:  (invalid)
    r 1050=00000400             #  4:  (invalid)
    r 1054=00000400             #  5:  (invalid)
    r 1058=00000400             #  6:  (invalid)
    r 105C=00000400             #  7:  (invalid)
    r 1060=00000400             #  8:  (invalid)
    r 1064=00000400             #  9:  (invalid)
    r 1068=00000400             # 10:  (invalid)
    r 106C=00000400             # 11:  (invalid)
    r 1070=00000400             # 12:  (invalid)
    r 1074=00000400             # 13:  (invalid)
    r 1078=00000400             # 14:  (invalid)
    r 107C=00000400             # 15:  (invalid)

    r 2000=22222222             # Test page #2
    r 3000=33333333             # Test page #3


    # Test program...

    r 200=41000800              # LA    R0,X'800'       R0 = x'800'
    r 204=1A00                  # AR    R0,R0           R0 = x'1000'

    r 206=1810                  # LR    R1,R0           R1 = x'1000' --> Test page #1

    r 208=1820                  # LR    R2,R0           R2 = x'1000'
    r 20A=1A22                  # AR    R2,R2           R2 = x'2000' --> Test page #2

    r 20C=B7000300              # LCTL  0,0,x'300'      CR0 <-- DAT format control
    r 210=B7110600              # LCTL  1,1,x'600'      CR1 <-- PTO
    r 214=B20D0000              # PTLB  ,               Purge TLB
    r 218=82000700              # LPSW  x'700'          Enable DAT mode

    r 21C=58001000              # L     R0,0(,R1)       R0 <-- x'00001040' (Test page #1)
    r 220=58002000              # L     R0,0(,R2)       R0 <-- x'22222222' (Test page #2)

    r 224=D20310480A00          # MVC   PTE#2,NEWPTE#2  Update PTE #2 --> Test page #3
    r 22A=B20D0000              # PTLB  ,               Purge TLB

    r 22E=58001000              # L     R0,0(,R1)       R0 <-- x'00001040' (Test page #1)
    r 232=58002000              # L     R0,0(,R2)       R0 <-- x'33333333' (Test page #3)

    r 236=82000400              # LPSW  x'400'          Successful completion

    t+                          # Enable intruction tracing...
    restart                     # Begin test...

    pause 0.1                   # Wait for an instant

    *
    *
    *
    *
    * --------------------------------------------------------------
    *
    *       Display registers...
    *
    gpr
    *
    *       The above R0 SHOULD be x'33333333' from Test page #3...
    *
    * --------------------------------------------------------------
    *
    *       Disassemble Test page #2... (default PSW mode)
    *
    u 2000.4
    *
    *       The above SHOULD disassemble test page #3 = 33333333...
    *
    * --------------------------------------------------------------
    *
    *       Disassemble Test page #2... (forced real mode)
    *
    u R2000.4
    *
    *       The above SHOULD disassemble test page #2 = 22222222...
    *
    * --------------------------------------------------------------
    *
    *       Disassemble Test page #2... (forced virtual mode)
    *
    u V2000.4
    *
    *       The above SHOULD disassemble test page #3 = 33333333...
    *
    * --------------------------------------------------------------
    *
    *       Disassemble Test page #2... (forced primary mode)
    *
    u P2000.4
    *
    *       The above SHOULD disassemble test page #3 = 33333333...
    *
    * --------------------------------------------------------------
    *
    *


    #########  END OF TEST #56  #########
    #########  END OF TEST #56  #########
    #########  END OF TEST #56  #########


Apply the above patch to current hyperion and then run the above script ("script myscript.rc") and you can see the bug occur.

Then change DOWHAT to FIXIT and rebuild Hyperion and run the script again. It should work properly this time.

I will be devising and committing a more thorough/complete patch shortly.

Thank you again Peter for your fantastic research. The bug was easy to verify/reproduce and easy to fix thanks to your hard work. It's people like you that make Hercules great! :)

**Comment by ivan-w** [comment]
Just my $.02 but...

Isn't this another problem with 4K pages being emulated on a 2K pages 
system ? (internally all storage is 2K in hercules *except* if S/370 is 
not generated as an architecture).

--Ivan

**Comment by Fish-Git** [comment]
Ivan wrote:
> Isn't this another problem with 4K pages being emulated on a 2K pages 
> system?

How so?

> (internally all storage is 2K in hercules *except* if S/370 is 
> not generated as an architecture).

And this is relevant to this issue.......... how?

**Comment by ivan-w** [comment]
Because there are places in translation assuming 2K pages is the page 
size and others when translation is assuming 4K page sizes... And 
depending on the environment (especially whether you are running the CPU 
thread - in an architectured environnment and the Console and/or Channel 
thread in a non architectured environment) the actual architecture can 
be mistaken. This can also apply to SIE where you are switching 
environments.

- Channel is not an issue since it always sees storage as real (and not 
logical)
- Sie had the issue once (when TPROT would return the wrong result when 
issuing TPROT in emulated S/370 on S/390 host if the page was above base 
4K page +2K)
- Console functions are not architectured (are not running under the CPU 
thread and are architecture independant)...

So that's why it came up as a possible issue (but maybe it isn't)

--Ivan

**Comment by Fish-Git** [comment]
I do not believe the guest's architected page size has anything to do with this issue, nor vice-versa.

The issue is purely a TLB lookup issue, and the TLB logic always uses 2K for 370 and 4K for 390 and 900.

A tlbID of zero is invalid and will never appear in an active TLB entry. That is why copy_regs does:

    memset(&newregs->tlb.vaddr, 0, TLBN * sizeof(DW));

This is supposed to invalidate ALL entries in the TLB thereby forcing translate_addr's TLB lookup test to always fail thereby forcing a full translation (TLB miss).

When regs->tlbID is zero *AND* all TLB vaddr fields in the regs copy are all zero, then the above condition is always true for any virtual address below 0x7FC00000 (TLBID_PAGEMASK), thereby increasing the likelihood(*) of a TLB lookup succeeding (and returning a bogus/stale pte) instead of always failing (thereby forcing a full address translation which should *always* return valid results).

Make sense?

-- 
"Fish" (David B. Trout)
Software Development Laboratories
http://www.softdevlabs.com
mail: fish@softdevlabs.com

(*) The increase in likelihood may still be very small (depending on other circumstances(**)), but it is greater than zero instead of always being zero like it should be.

(**) Such as how the Hercules host's memory manager behaves for malloc requests.

**Comment by ivan-w** [comment]
Le 05/07/2015 22:02, Fish-Git a écrit :
>
> The issue is purely a TLB lookup issue, and the TLB logic always uses 
> 2K for 370 and 4K for 390 and 900.
>

Nope... The TLB always uses 2K... no matter whether the host 
architecture is 2K or 4K...


--Ivan

**Comment by Fish-Git** [comment]
feature.h:

[...]
#undef TLB_PAGEMASK
#undef TLB_BYTEMASK
#undef TLB_PAGESHIFT
[...]
#if __GEN_ARCH == 370
[...]
#define TLB_PAGEMASK  0x00FFF800
#define TLB_BYTEMASK  0x000007FF
#define TLB_PAGESHIFT 11
[...]
#elif __GEN_ARCH == 390
[...]
#define TLB_PAGEMASK  0x7FFFF000
#define TLB_BYTEMASK  0x00000FFF
#define TLB_PAGESHIFT 12
[...]
#elif __GEN_ARCH == 900
[...]
#define TLB_PAGEMASK  0xFFFFFFFFFFFFF000ULL
#define TLB_BYTEMASK  0x0000000000000FFFULL
#define TLB_PAGESHIFT 12
[...]
#else
#warning __GEN_ARCH must be 370, 390, 900 or undefined
#endif


-- 
"Fish" (David B. Trout)
Software Development Laboratories
http://www.softdevlabs.com
mail: fish@softdevlabs.com
