### ISSUE TITLE
Console panel does not restore terminal settings on exit (UNIX only)

### ISSUE THREAD

**Issue by jphartmann** [hercules-390/hyperion#68]
After quitting Hercules, the terminal no longer echos keystrokes; stty echo (possibly with stty cooked) restores normal operation.  Hercules should clean up after itself.

An option to disable panel entry and just write to standard output would be nice.

**Comment by Fish-Git** [comment]
Looking at panel code, pane_display (in panel.c) does the following at startup:

    hdl_adsc("panel_cleanup",panel_cleanup, NULL);

    ...

    /* Put the terminal into cbreak mode */
    set_or_reset_console_mode( keybfd, 1 );

and this at shutdown:

    static void panel_cleanup(void *unused)
    {
      ...

      /* Restore the terminal mode */
      set_or_reset_console_mode( keybfd, 0 );

leading us to the `set_or_reset_console_mode` function in hconsole.c:

    #ifdef HAVE_TERMIOS_H
    static struct termios saved_kbattr;  // (saved value so we can later restore it)
    #endif

    // 'save_and_set' = 1 --> just what it says; 0 --> restore from saved value.

    int set_or_reset_console_mode( int keybrd_fd, short save_and_set )
    {
    #ifdef HAVE_TERMIOS_H

        ...code...

    #else

        UNREFERENCED( keybrd_fd );
        UNREFERENCED( save_and_set );

    #endif

        return 0;
    }

compelling me to ask the logical question: is `HAVE_TERMIOS_H` #defined in your config.h header?

Or, if that's not it, do you see a bug in the above Linux version of our `set_or_reset_console_mode` function?

**Comment by jphartmann** [comment]
I do have termios.h and the define.

I can see the code in hconsole.c, but I cannot find the console_mode function definitions nor Wincon.h where they are no doubt defined.

Please advise.

**Comment by Fish-Git** [comment]
`wincon.h` is a Windows header.  :smile:

Are you sure you are looking at the right version of the function? The `set_or_reset_console_mode` function for Linux starts after line number 583 in hconsole.c.

**Comment by Fish-Git** [comment]
I believe the following is the reference material you are probably looking for:

* [The Open Group Base Specifications Issue 7] (http://pubs.opengroup.org/onlinepubs/9699919799/)
* [tcgetattr] (http://pubs.opengroup.org/onlinepubs/9699919799/functions/tcgetattr.html)
* [tcsetattr] (http://pubs.opengroup.org/onlinepubs/9699919799/functions/tcsetattr.html)
* [termios.h] (http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/termios.h.html)

**Comment by jphartmann** [comment]
My bad.  I was looking at the windows stuff.

Your chapter and verse is spot on.

Saving is from the file descriptor parameter, but restore is always to stdin.  I cannot immediately see whether panel.h calls the save function with fd = 0; if the fd is -1, saving will fail (nothing will be saved), and zeros will be restored.

I suppose I shall have to instrument it.  Chances are that the restore function is not called.

**Comment by Fish-Git** [comment]
Thought so.  :smirk:

Let us know what you find. In the mean time, regarding your other comment:

> An option to disable panel entry and just write to standard output would be nice.

I'm not sure if this is what you're looking for, but were you aware hercules can also be run in pure tty (i.e. line) mode? It's called `herclin` and Ivan wrote it. It reads from stdin and writes to stdout. No "panel mode" at all. Just a simple command-line program that runs Hercules. Try it!

**Comment by Fish-Git** [comment]
FYI: I believe `herclin` was written so that Hercules could be run as a "daemon" (is that the right term? i.e. as a headless system service/process). I believe the '-d' command-line option was created for that purpose as well.

**Comment by ivan-w** [comment]
Ooops...

I think herclin was written as an experiment by yours truly... quite 
some time ago (an experiment for using some generalized API for console I/O)

--Ivan

**Comment by jphartmann** [comment]
impl.c line 656 has

sysblk.daemon_mode = !isatty(STDERR_FILENO) && !isatty(STDOUT_FILENO);

Shouldn't this be an OR, or just testing standard out?   But given that -d has no effect, perhaps this is a red herring?

**Comment by Fish-Git** [comment]
I'm not sure about the above test nor why you say -d has no effect but neither directly pertains to the original issue: "Console panel does not restore terminal settings on exit ". I believe this issue's **base problem** has _something_ to do with the code in either `hconsole.c` (likely) or `panel.c` (just as likely since it calls it).

Have you "instrumented it" yet? Have you been able to determine the cause yet?

**Comment by jphartmann** [comment]
The exit console command restores the terminal settings; the quit command does not.  Doctor, doctor...

**Comment by Fish-Git** [comment]
I'm not sure why you say the quit command doesn't. Both are _exactly_ the same thing:

    COMMAND( "exit", quit_cmd, SYSALLNDIAG8, exit_cmd_desc, NULL          )
    COMMAND( "quit", quit_cmd, SYSALLNDIAG8, quit_cmd_desc, quit_cmd_help )
    #define exit_cmd_desc "(Synonym for 'quit')"

If they are not behaving identically for you then there's something very unusual about your build/installation of Hercules and/or your host system in general and we should probably try to identify that.

**Comment by jphartmann** [comment]
Hmm.  Perhaps I pulled some update that fixed things.
