### ISSUE TITLE
Program interrupt loop is not recognised in a clear z/Architecture machine

### ISSUE THREAD

**Issue by jphartmann** [hercules-390/hyperion#79]
Try this:

```
sysclear
archmode z     
restart
```
The program loops forever taking interrupts.

**Comment by jphartmann** [comment]
The "program" has a correct PSW (all zeros is valid, even if unusual).  Thus the program check at 0 causes another program check at 0.  This is not a program interrupt loop.

**Comment by jphartmann** [comment]
Anyhow, this issue has now been fixed so that a program check due to a PSW that addresses an invalid instruction is also recognized as an infinite loop that will never exit, even though it technically is not an infinite loop in loading the program new PSW.

**Comment by Fish-Git** [comment]
Adding "Enhancement" label (since original issue wasn't really a Hercules bug) and closing issue since a further enhancement to Hercules has apparently resolved it.
