### ISSUE TITLE
runtest script contains hard-coded top-level Hercules directory name "hyperion"

### ISSUE THREAD

**Issue by dasdman** [hercules-390/hyperion#82]
The runtest script incorrectly uses a hard-coded top-level directory name of "hyperion". Consequently, when working with a top-level directory name other than "hyperion" as one might in working with concurrent efforts in parallel, runtest fails to complete.

**Comment by jphartmann** [comment]
It does not.  It uses a default of hyperion.

"make check" will use the correct path, as configured.

**Comment by dasdman** [comment]
"make check" does not run single tests. From Makefile:
```Makefile
check:
	$(top_srcdir)/tests/runtest $(top_srcdir)/tests
```
To do so, one must follow the directions for a single test per lines 36-38 of the runtest script (script code in error follows example). From the console/terminal:
```bash
cd ~/Hercules/Hyperion-QA
../Hyperion-QA/runtest - mainsize
cat: ../hyperion/tests/mainsize.tst: No such file or directory
REX0003E: Error 3:  Failure during initialization
REX0534E: Error 3.901:  Failure during initialization: Program "../hyperion/tests/redtest.rexx" was not found
```
---------------------------------------------------------------------------------------------------------
runtest script:
```bash
Line 36:  # To run a specific test case:
Line 37:  #       ../hyperion/tests/runtest - <fname>
Line 38:  # Again, be sure to omit the extension.

Line 45:  dir=${1:-../hyperion/tests}
Line 46:  if [ "$dir" == "-" ] ; then
Line 47:          dir=../hyperion/tests
Line 48:  fi
```
------------------------------------------------------------------------------------------------------------
Temporary bypass is to ensure that the actual directories are not named "hyperion" and then define or redefine a temporary symbolic link for "hyperion" to the current Hyperion directory in use.

**Comment by jphartmann** [comment]
Just specify the path to the source tests directory as the first argument instead of the hyphen:
```
../Hyperion-QA/tests/runtest ../Hyperion-QA/tests mainsize
```
Perhaps one could glean the path to the tests from the executable ($0).

**Comment by jphartmann** [comment]
Mark wrote:
```
    dir=${1:-$(pwd)/tests}
    if [ "$dir" == "-" ] ; then
            dir=$(pwd)/tests
    fi
```
"Should do the job..."

No, this makes the assumption that your present working directory is the source directory.  This is very much frowned on in the UNIX community where a separate object directory is preferred.

Compiling outside the source directory means that one can have one source tree on a server and configure multiple object directories (as have I explained in `INSTALL`).

At the moment I have configured in the `atom` directory.  The source is `../hyperion`.

As it is, `runtest` should be able to be cajoled into your desired behaviour by specifying the first argument accordingly.  If you cannot, that is definitely a bug on my part.

**Comment by jphartmann** [comment]
Here is a shell script that runs a test in a totally different directory.
```
#!/bin/bash
# Run a test case locally.

dir=/usr/data/src/hercules/

fn=$1.tst
if [ "$2" != "noexit" ] ; then
        echo exit|cat $fn - >atest.in
        fn=atest.in
        redir='2>&1'
fi
eval $dir/atom/hercules -f $dir/hyperion/tests/tests.conf -r $fn >atest.out $redir
rexx redtest.rexx atest.out                   
```

**Comment by dasdman** [comment]
Full update submitted. runtest now determines the proper directories for both tests and the execution of Hercules by runtest, regardless of current path in use for all forms. The proper default directory under BASH is provided by:
```sh
dir_runtest="$(dirname "${BASH_SOURCE[${#BASH_SOURCE[@]} - 1]}")"
```
The proper Hercules directory is provided by:
```sh
dir_hercules="$dir_runtest/.."
```

**Comment by jphartmann** [comment]
No it does not.  Read INSTALL.

**Comment by Fish-Git** [comment]
Reviewing our current *Nix runtest script it appears this issue has long been resolved now, so I am going to go ahead and close this issue. Please re-open it again if it is still a problem. Thank you.
