### ISSUE TITLE
Commit 5b10f595c3cc287b78742216eac10db51e4957f3 breaks building Hercules outside the source tree

### ISSUE THREAD

**Issue by jphartmann** [hercules-390/hyperion#84]
You cannot assume that the executable is built in the source tree.  Please read INSTALL in the source tree.

**Comment by jphartmann** [comment]
../hyperion/tests/runtest: line 69: ../hyperion/tests/../hercules: No such file or directory

**Comment by dasdman** [comment]
Not disputing that more work needs to be done. The original invocation as ./hyperion failed in more scenarios, including the incorrect generation of thousands of processes in one scenario. Script must be updated to use make information as to location, and to check for which location to use when not invoked via make check.

**Comment by jphartmann** [comment]
Please enumerate these scenarios so I can understand them.

I my setup ./hercules is the way to invoke hercules, but I can add test for the existence of the executable.

**Comment by Fish-Git** [comment]
(PING!)  Has this issue been resolved yet?  If so, please close.  If not, what still needs to be done?

**Comment by Fish-Git** [comment]
Closing due to no response.
