### ISSUE TITLE
redtest.rexx stalls when Hercules segfaults but terminates properly

### ISSUE THREAD

**Issue by dasdman** [hercules-390/hyperion#88]
When running runtest and Hercules experiences a segfault, redtest.rexx may stall on the `linein(in)` function call in redtest.rexx line 79 when processing. Ctrl-X breaks.

Fix is to change the `do forever` on line 77 to `do while lines(in)`.

**Comment by jphartmann** [comment]
Blush.

Fixed a5548bd67042a1c1b402663d2f23f6b182270937
