### ISSUE TITLE
Make issue on mac os 10.9.4

### ISSUE THREAD

**Issue by hegoku** [hercules-390/hyperion#9]
![qq20140714-1](https://cloud.githubusercontent.com/assets/4908143/3571926/834874f8-0b62-11e4-9c3c-be194fa1e4c4.png)
just like the image i uploaded,when i use "make",then it says:

```sh
clang: error: unknown argument: '-m128bit-long-double' [-Wunused-command-line-argument-hard-error-in-future]
clang: note: this will be a hard error (cannot be downgraded to a warning) in the future
make[2]: *** [decContext.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```
And i also use ``ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future make`` to solve the problem,but i didn't work....

**Comment by dlrourke** [comment]
How are things progressing on resolving this issue?  I understand how to get around the issue by removing the "-m128bit-long-double" option from line 2191 (as of 26-Jan-2015) of configure.ac, but wonder what the impact of this change is on the performance of the Hyperion version of Hercules on OS X Yosemite (and I suppose Mavericks).

**Comment by herc4mac** [comment]
>>  but wonder what the impact of this change is on the performance of the Hyperion version of
 >>  Hercules on OS X Yosemite 

why worry since there is nothing that You/we can do about it ???

**Comment by hackob** [comment]
To bypass this error just use `--enable-optimization=no` as configure option:

example: `$ ./configure --enable-optimization=no`

**Comment by Fish-Git** [comment]
The workaround (offered by @herc4mac in another github issue) is to use:

    ./configure --enable-optimization="-O3 -march=native -fomit-frame-pointer" —prefix=whatever

@herc4mac is supposedly working on fixing `configure.ac` which is where the bug is.

**Comment by krauseralf** [comment]
Here is the procedure I've used to install Hyperion on OS X El Capitan:

**cd <directory with hyperion source>**
**util/bldlvlck**

**If you get an output like this one everything is fine:**
This utility will check the level of various utilities needed to build
hercules. Checking is done against versions that are KNOWN to work.
This doesn't mean a build will NOT succeed with older versions
of the utilities, but will give a hint as to what package may need
an upgrade if the build ever fails with some odd reason.


OK	autoconf requires 2.64, found 2.69

OK	automake requires 1.9, found 1.15

OK	flex requires 2.5, found 2.5.35

OK	gawk requires 3.0, found 4.1.3

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
OK	gcc requires 3, found 7.0.0

OK	grep requires 1, found 2.5.1

Apple/Darwin ==> custom version parsing!
OK	m4 requires 1.4.6, found 1.4.6

OK	make requires 3.79, found 3.81

OK	perl requires 5.6, found 5.18.2

Apple/Darwin ==> sed changed to gsed!
OK	gsed requires 3.02, found 4.2

macbook:~ rkrause$ 

**_If you need a different or newer version the tool will tell you._**

**./autogen.sh**
**CFLAGS="-O3 -D_FORTIFY_SOURCE=0" CC="gcc" ./configure --enable-optimization=no**
**make**

**_You will get some warning. But they can safely be ignored._**

**./hercules -f <path and file name of a hercules config file>**

Connect with a 3270 Emulator to hercules and ipl the system.
If everything is fine perform the last step:
**sudo make install**


That was it. For me everything was working fine and hercules is working as expected.
I didn't had any problems with this procedure. And the best of all was that I didn't had to edit any file.
I just had to install gawk and gsed.

I hope this helps!

**Comment by srorso** [comment]
Looking into this (don't ask why), it appears that the -m128bit-long-double determines the storage allocation for variables of the `long double`  floating point type (128-bits versus the minimally required 96 bits).   Long double is used only to hold intermediate results in the emulation of the Store System Information (STSI) instruction.  The option is set only on x86 architectures.  I suspect the coding in configure.ac to set this option can be removed.

**Comment by Fish-Git** [comment]
I agree, Steve.

To that end I've just committed a change (commit 9998029da3f1dddcfb01ac338792d39fc792ff37) that removes the `-m128bit-long-double` option altogether, so I am going to close this issue.

@herc4mac : feel free to re-open this issue if you feel it's necessary. Thanks.

**Comment by ivan-w** [comment]
I think it's simply because "clang" doesn't support this option...

Only a wild guess

--Ivan

**Comment by Fish-Git** [comment]
> I think it's simply because "clang" doesn't support this option...

That could well be true, but given Steve's findings it's simply not worth it (IMO) to go to the trouble of adding a configure.ac test to check whether the option is supported or not and then have to test for that in the auto-optimize logic (to prevent it from being used if it isn't) when simply removing the option altogether is a much more simple and straightforward solution.
