### ISSUE TITLE
s37x dynamic module MVCLE (and possibly other?) instruction(s) issue(s)

### ISSUE THREAD

**Issue by Fish-Git** [hercules-390/hyperion#90]
#### Background

As pointed out in the `hercules 3.12 MVCLE inconsistency` thread in the main Hercules-390 group, the MVCLE instruction is currently incorrectly implemented for S/370 mode builds of Hercules.

The MVCLE instruction (opcode A8) is not officially defined as being part of the System/370 architecture.  It does not appear in any of the S/370-related Principles of Operation manuals, as do any any of the other S/390 and/or z/Arch instructions either.

Since some of the newer z/Arch instructions are quite handy to use (and since there is nothing in any of the Principles of Operations manuals disallowing it), the `s37x` module was written to allow certain instructions not normally/officially defined for the S/70 architecture to be optionally supported anyway via the `ldmod s37x` command.

#### The bug

Whether a given instruction is supported on a given architecture or not is controlled via the opcode tables' `GEN...` macros defined in source module opcode.c.  If `GENx370x390x900` is coded for an instruction it will be supported by all three architectures. If `GENx___x390x900` is coded instead, then the instruction will only be supported for the 390 and z architectures but not for the 370 architecture. If such an instruction were attempted to be executed in 370 mode, a Program Check Interruption would result.

To allow the `s37x` loadable module to dynamically enable/disable support for certain instructions for 370 mode, a new set of `GEN...` macros were defined to indicate *optional* 370 mode support for an instruction by coding `x37X` in the `GEN...` macro instead of the normal `x370`.  For example, coding `GENx37Xx390x900` indicates the instruction is an *optional* 370 instruction which can be dynamically activated (enabled) via the `ldmod s37x` command.

Unfortunately however, the opcode.c `GEN...` macro for the MVCLE (opcode A8) instruction was incorrectly coded as `GENx370x390x900` instead of `GENx37Xx390x900`, causing the instruction to always be valid in 370 mode when technically is should not be. Furthermore, support for actually *providing* the optional support for it in 370 mode was missing altogether in the `s37x` module (source file `s37x.c`).

This issue was created to address this oversight/bug and to provide a means of tracking additional work that needs to be done to the `s37x` module.

#### The quick fix

The quick fix (commit a20a01c12b483e80adb47a76bb70f9aa34bca261) is to simply code `x37X` in the opcode.c's `GEN...` macro entry for opcode A8 (MVCLE), *and* to add the missing `INST37X` macro statement to the `s37x` module's instruction table in source file `s37x.c`.

With this simple fix in place the MVCLE (opcode A8) now properly Program Checks for the normal/default 370 mode case, and properly successfully executes *only* when the `ldmod s37x` command is used to activate/enable the optional set of 370-mode instructions.

#### The additional work that should also be done (IMO)

While the previously mentioned quick fix addresses (resolves) the immediate problem, it does not resolve the following issues (which in this author's opinion still need to be (*should* be) resolved):

<ol>
<li>First and foremost the s37x module should really be a dyninst module and not a normal module.</li>
<p>
That is to say, the module should not be manually patching the instruction tables like it currently is.  Instead, it should use our existing dyninst technique. This is important from a maintainability / quality assurance point of view. If the layout of the instruction opcode tables or the technique for dynamically updating them ever changes, there should ideally be only once place where the change needs to be made. You should always use the officially supported technique when one is available.
<p>
Additionally, since it is not currently coded  as a dyninst module as it should be, doing an "lsmod" after having loaded the module (ldmod s37x) does not list all of the instructions/opcodes that the module is providing like it should be like other dyninst modules do (such as dyncrypt):
<p>
<pre>ldmod s37x

HDL: loading module s37x...
HDL: module s37x loaded

lsmod

HDL: dll type = load, name = s37x, flags = (unloadable, not forced)
HDL: dll type = load, name = hdt1052c, flags = (unloadable, not forced)
HDL:  symbol = panel_command, loadcount = 2, owner = hdt1052c
HDL:  devtype(s) = 3215-C 1052-C
HDL: dll type = load, name = dyngui, flags = (unloadable, not forced)
HDL:  symbol = panel_command, loadcount = 0, owner = dyngui
HDL:  symbol = debug_cd_cmd, loadcount = 1, owner = dyngui
HDL:  symbol = debug_cpu_state, loadcount = 1, owner = dyngui
HDL:  symbol = daemon_task, loadcount = 1, owner = dyngui
HDL:  symbol = panel_display, loadcount = 1, owner = dyngui
HDL: dll type = load, name = dyncrypt, flags = (unloadable, not forced)
HDL:  instruction = perform_cryptographic_key_management_operation, opcode = B928, archmode = z/Arch
HDL:  instruction = perform_cryptographic_key_management_operation, opcode = B928, archmode = ESA/390
HDL:  instruction = perform_cryptographic_computation, opcode = B92C, archmode = z/Arch
HDL:  instruction = perform_cryptographic_computation, opcode = B92C, archmode = ESA/390
HDL:  instruction = cipher_message_with_output_feedback, opcode = B92B, archmode = z/Arch
HDL:  instruction = cipher_message_with_output_feedback, opcode = B92B, archmode = ESA/390
HDL:  instruction = cipher_message_with_cipher_feedback, opcode = B92A, archmode = z/Arch
HDL:  instruction = cipher_message_with_cipher_feedback, opcode = B92A, archmode = ESA/390
HDL:  instruction = cipher_message_with_counter, opcode = B92D, archmode = z/Arch
HDL:  instruction = cipher_message_with_counter, opcode = B92D, archmode = ESA/390
HDL:  instruction = cipher_message_with_chaining, opcode = B92F, archmode = z/Arch
HDL:  instruction = cipher_message_with_chaining, opcode = B92F, archmode = ESA/390
HDL:  instruction = compute_message_authentication_code, opcode = B91E, archmode = z/Arch
HDL:  instruction = compute_message_authentication_code, opcode = B91E, archmode = ESA/390
HDL:  instruction = cipher_message, opcode = B92E, archmode = z/Arch
HDL:  instruction = cipher_message, opcode = B92E, archmode = ESA/390
HDL:  instruction = compute_last_message_digest, opcode = B93F, archmode = z/Arch
HDL:  instruction = compute_last_message_digest, opcode = B93F, archmode = ESA/390
HDL:  instruction = compute_intermediate_message_digest, opcode = B93E, archmode = z/Arch
HDL:  instruction = compute_intermediate_message_digest, opcode = B93E, archmode = ESA/390
HDL: dll type = load, name = hdteq, flags = (unloadable, not forced)
HDL:  symbol = hdl_device_type_equates, loadcount = 1, owner = hdteq
HDL: dll type = main, name = *Hercules, flags = (not unloadable, not forced)
HDL:  symbol = replace_opcode, loadcount = 1, owner = *Hercules
HDL:  symbol = panel_display, loadcount = 0, owner = *Hercules
HDL:  symbol = panel_command, loadcount = 0, owner = *Hercules
HDL:  symbol = parse_args, loadcount = 0, owner = *Hercules
HDL:  devtype(s) = 9336 9335 9332 9313 3370 3310 0671 9345 3390 3380 3375 3350 3340 3330 2314 2311 2305</pre>
<p>
So that's the first thing that will still need to be fixed.

<li>The second thing that will still need to be done is an audit of the instructions / features the module is supposedly providing to ensure there aren't any other instruction(s) which are also incorrectly implemented (e.g. opcode.c's "GEN" macro incorrectly coded with x370 instead of x37X like it was for MVCLE and/or completely missing support in the s37x module for an instruction which it *should* be providing support for (again like it was for MVCLE).</li>
<p><p>
It also would help to add a few extra comments to the #if defined(OPTION_370_EXTENSION) code block in the feat370.h header (as well as some corresponding comments in the s37x module's source file(s) as well) explaining that should support for new instructions / feature sets be added to the #if defined(OPTION_370_EXTENSION) code block in the future, that one should take care to ensure all of the required pieces are properly in place (e.g. the all important coding of "x37X" in 'GEN' macros in opcode.c as well as the support code to call it in the s37x dyninst module itself).
<p><p>
</ol>
<hr>
##### Assignment

I am assigning this issue to you @ivan-w since the `s37x` module was written by you. If you do not wish to take ownership/responsibility for this issue then please simply change the ownership for this issue back to "unassigned" and we'll try to find someone else to do it. Thanks.

**Comment by jphartmann** [comment]
Don't forget to give CLCLE (A9) the same treatment

**Comment by Fish-Git** [comment]
Ivan isn't interested.  Oh well.  :(

**Comment by jphartmann** [comment]
This issue is also present with CSXTR, which delivers 64 bits into a general register.  How anyone can imagine this in ESA mode is beyond me.

**Comment by herc4mac** [comment]
> This issue is also present with CSXTR, which delivers 64 bits into a general register. How anyone can imagine this in ESA mode is beyond me.

the same brilliant mind who wrote

#if defined(FEATURE_EXTENDED_TRANSLATION_FACILITY_3)
DEF_INST(convert_utf16_to_utf32);
DEF_INST(convert_utf32_to_utf16);
DEF_INST(convert_utf32_to_utf8);
DEF_INST(convert_utf8_to_utf32);
DEF_INST(convert_to_binary);
DEF_INST(convert_to_decimal);
#endif /*defined(FEATURE_EXTENDED_TRANSLATION_FACILITY_3)*/

cheers 
enrico
