### ISSUE TITLE
Integrated console cmdpref enhancements requested

### ISSUE THREAD

**Issue by somitcw** [hercules-390/hyperion#91]
1. The same cmdpref should not be allowed for multiple integrated consoles.
Any attempt to specify one already in use should be rejected.
The default of slash "/" should be changed to a list of valid cmdpref that select
the first available at that time from the list.
.
2. All output messages from the operating system for an integrated console should have the
cmdpref prepended just like commands and replies from the user and Hercules.rc files are now.

**Comment by Fish-Git** [comment]
Closed by commit 74254a538e8e01bc1214df188960f284f12dc19f.
