### ISSUE TITLE
Utility dasdisup references uninitialized variable multitxt

### ISSUE THREAD

**Issue by srorso** [hercules-390/hyperion#99]
Dasdisup references variable multitxt in routine resolve_xctltab() in dasdisup.c, but the variable is initialized only for SVCLIB members that have more than one txt record.  The variable is part of a structure MEMINFO, which is malloc'd as an array but not initialized at the start of dasdisup processing.  If the area containing multitxt is by happenstance zero when malloc()'d, dasdisup works fine.  If not, then members that should participate in xctl table resolution are excluded.  The result is a sysres volume that cannot be ipl'd by OS/360--in my case, it fails with a loop after completing some initialization.  

All other fields in MEMINFO are assigned values for every member processed by dasdload.  

For whatever reason, it appears that when dasdisup.c is compiled with VS2008, the area returned by malloc() area is pretty clean.  At least clean enough to allow dasdisup.c to generate a correct-enough SVCLIB to IPL the MFT 21.0 driver system used in Jay Maynard's MVT generation procedure.  Builds performed by Visual Studio 2015 Community Edition result in a fairly "dirty" area being returned by malloc().  

Working and failing builds done on Windows 10 32-bit.

The relevant code has existed unchanged in both 3.xx and 4.00 since 2001, so a malloc() for about 15,000 bytes on other platforms must usually return a clean area.  

I have tested the correction in Pull Request #98 by building OS/360 MVT using [Jay Maynard's instructions](http://www.conmicro.com/hercos360/).

**Comment by Fish-Git** [comment]
Fixed by commit 6989a0d4847e9acd3de8d006b9fdfac8d4c73ddf.
